services:
  web:
    image: ${LATEST_IMAGE}
    pull_policy: always
    env_file: .env
    ports:
      - ${PORT}:${PORT}
  nginx:
    image: myshoka/nginx:${DOMAIN}
    pull_policy: always
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
      args:
        - SSL_CERT_DIRECTORY=${SSL_CERT_DIRECTORY}
        - SSL_KEY_DIRECTORY=${SSL_KEY_DIRECTORY}
        - DOMAIN=${DOMAIN}
    ports:
      - 80:80
      - 443:443
    environment:
      - PORT=${PORT}
      - DOMAIN=${DOMAIN}
      - SSL_ACME_DIRECTORY=${SSL_ACME_DIRECTORY}
