services:
  web:
    image: ${LATEST_IMAGE}
    pull_policy: always
    env_file: .env
    volumes:
      - type: bind
        source: /.env
        target: /.env
    ports:
      - ${PORT}:${PORT}
  nginx:
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80
    environment:
      - PORT=${PORT}
