services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.5
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html 
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes_from: 
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${DOMAIN_EMAIL}
  web:
    image: ${LATEST_IMAGE}
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    build:
      args:
        - ENVIRONMENT=${NODE_ENV}
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=${PORT}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${DOMAIN_EMAIL}
