services:
  web:
    image: ${LATEST_IMAGE}
    pull_policy: always
    env_file: .env
    ports:
      - ${PORT}
  nginx:
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
    volumes:
      - ./config:/etc/nginx/templates
    ports:
      - 80:80
    environment:
      - PORT=${PORT}
