services:
  web:
    image: ${LATEST_IMAGE}
    pull_policy: always
    env_file: .env
    ports:
      - ${PORT}:${PORT}
  nginx:
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
      no_cache: true
    ports:
      - 80:80
    environment:
      - PORT=${PORT}
