services:
  web:
    image: ${LATEST_IMAGE}
    pull_policy: always
    env_file: .env
    ports:
      - ${PORT}:${PORT}
  nginx:
    image: myshoka/nginx:${DOMAIN}
    pull_policy: always
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    env_file: .env