FROM node:21.6.1-alpine3.18 as build
ARG ENVIRONMENT
WORKDIR /build
COPY . .
RUN npm ci
RUN npm run build:client -- --env environment=${ENVIRONMENT}
RUN npm run build:server -- --env environment=${ENVIRONMENT}

FROM node:21.6.1-alpine3.18
ENV PORT=3000
WORKDIR /app
COPY ./package-lock.json .
COPY ./package.json .
RUN npm ci
COPY ./public ./public
COPY --from=build /build/src/dist/ ./src/dist
COPY --from=build /build/public/dist/ ./public/dist
CMD ["node", "./src/dist/node-bundle"]
EXPOSE $PORT