FROM node:21.6.1-alpine3.18 as build
ENV NODE_ENV=development
WORKDIR /build
COPY . .
RUN npm ci
RUN npm run build --environment=${NODE_ENV}

FROM node:21.6.1-alpine3.18
ENV PORT=3000
WORKDIR /app
COPY ./package-lock.json .
COPY ./package.json .
RUN npm ci
COPY ./public ./public
COPY --from=build /build/src/dist/ ./src/dist
COPY --from=build /build/public/dist/ ./public/dist
CMD ["node", "./src/dist/node-bundle"]
EXPOSE $PORT