name: Build App

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Node.js app
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci
      - run: npm run build
