name: Build Node App and Deploy

# Only trigger, when the build workflow succeeded
on:
  push:
    branches:
      - "main"
  # For now on main push for testing

  #workflow_run:
  #  workflows: ["Node.js CI & Tests"]
  #  types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Node.js app
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci
      - run: npm run build

  create-image:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.ENVIRONMENT_REPO_ACCESS_TOKEN }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: myshoka/portfolio:latest-${{ github.sha }}

  update-build-version:
    runs-on: ubuntu-latest

    env:
      VERSION_CONFIG: version.yml

    steps:
      # uses yq to read yml files
      - name: setup yq
        uses: mikefarah/yq@master

      - name: checkout repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ env.VERSION_CONFIG }}
          sparse-checkout-cone-mode: false

      - name: update version
        run: |
          yq '.app-version' ${{ env.VERSION_CONFIG }}
          yq -i '.build |= . + 1' ${{ env.VERSION_CONFIG }}

  deploy:
    runs-on: ubuntu-latest

    env:
      ENV_CONFIG_PATH: envs/testing/
      ENV_CONFIG_FILE: settings.yml
      PATH_SOURCE_CHECKOUT: temp_folder

    steps:
      - name: setup yq
        uses: mikefarah/yq@master

      - name: checkout settings file
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ENVIRONMENT_REPO_URL }}
          path: ${{ env.PATH_SOURCE_CHECKOUT }}
          ref: "main"
          sparse-checkout: |
            ${{ env.ENV_CONFIG_PATH }}${{ env.ENV_CONFIG_FILE }}
          sparse-checkout-cone-mode: false

      - name: output workspace
        run: |
          cd $PATH_SOURCE_CHECKOUT
          cd $ENV_CONFIG_PATH
          yq '.resources' $ENV_CONFIG_FILE
      
