name: Build Node App and Deploy

# Only trigger, when the build workflow succeeded
on:
  push:
    branches:
      - "main"
  # For now on main push for testing

  #workflow_run:
  #  workflows: ["Node.js CI & Tests"]
  #  types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Node.js app
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci
      - run: npm run build

  create-image:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.ENVIRONMENT_REPO_ACCESS_TOKEN }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: myshoka/portfolio:latest

  
  deploy:
    runs-on: ubuntu-latest

    env:
      ENV_CONFIG: settings.yml

    steps:
      - name: get env file
        run: |
          curl -H "Authorization: token ${TOKEN}" ${{ secrets.ENVIRONMENT_REPO_URL }}/blob/main/envs/testing/settings.yml -o ${ENV_CONFIG}

      - name: output file contents
        run: yq '.resources' ${ENV_CONFIG}

      # uses yq to read yml files
      - name: setup yq
        uses: mikefarah/yq@master

