name: Build App

on:
  pull_request:
    branches: ["main"]

jobs:
  build-image:
    runs-on: ubuntu-latest

    outputs:
      build: ${{ steps.get_build_version.outputs.BUILD }}
      version: ${{ steps.get_build_version.outputs.VERSION }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: setup yq
        uses: mikefarah/yq@master

      - name: get current build version
        id: get_build_version
        run: |
          wget https://raw.githubusercontent.com/Kojolika/Portfolio/${GITHUB_REF_NAME}/${VERSION_FILE}
          VERSION=$(yq '.app-verison' ./${VERSION_FILE})
          BUILD=$(yq '.build' ./${VERSION_FILE})
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "BUILD=$BUILD" >> "$GITHUB_OUTPUT"
          echo "LATEST_IMAGE=${ENV_REPO}:latest-${VERSION}-${BUILD}" >> "$GITHUB_OUTPUT"
        
        env:
          VERSION_FILE: version.yml
          ENV_REPO: ${{ secrets.DOCKER_REPO_URL }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.LATEST_IMAGE }},:latest
          file: ./Dockerfile.web
        
        env:
          LATEST_IMAGE: ${{ steps.get_build_version.outputs.LATEST_IMAGE }}
