name: Deploy Build

on:
  push:
#  workflow_run:
#    workflows: ["Update Build Version"]
#    types: [completed]

env:
  LATEST_IMAGE: ${{ secrets.DOCKER_REPO_URL }}:latest-${{ github.sha }}

jobs:
  create-image:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.LATEST_IMAGE }}

  # For this deploy to work correctly, the EC2 instance needs to have docker and docker-compose installed
  # Then make sure the docker daemon is running
  EC2-deploy:
    needs: create-image
    runs-on: ubuntu-latest

    env:
      ENV_CONFIG_PATH: envs/testing/
      ENV_CONFIG_FILE: settings.yml
      ENV_REPO_CHECKOUT_PATH: temp_folder
      REPO_CHECKOUT_PATH: portfolio
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_IP: ${{ secrets.EC2_DEV_IP }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: set current runner path as env var
        run: |
          echo "WORK_DIR=$(pwd)" >> "$GITHUB_ENV"

      - name: setup yq
        uses: mikefarah/yq@master

      - name: checkout repo
        uses: actions/checkout@v4

      - name: checkout settings file
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ENVIRONMENT_REPO_URL }}
          path: ${{ env.ENV_REPO_CHECKOUT_PATH }}
          ref: "main"

      - name: get port and protocol settings
        run: |
          cd $ENV_REPO_CHECKOUT_PATH
          cd $ENV_CONFIG_PATH
          BASE_SETTINGS=$(yq '.resources' $ENV_CONFIG_FILE)
          PORT=$(yq '.deployment.ports.port' $BASE_SETTINGS)
          NETWORK_PROTOCOL=$(yq '.deployment.ports.protocol' $BASE_SETTINGS)
          echo "PORT=$PORT" >> "$GITHUB_ENV"
          echo "NETWORK_PROTOCOL=$NETWORK_PROTOCOL" >> "$GITHUB_ENV"

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: set ssh identity on github runner
        run: |
          mkdir -p $SSH_DIR
          cd $SSH_DIR
          echo "$SSH_KEY" > $SSH_PRIVATE_KEY_NAME
          chmod 600 $SSH_PRIVATE_KEY_NAME
          ssh-keyscan $EC2_IP >> known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add $SSH_DIR

        env:
          SSH_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.DEV_SSH_PUBLIC_KEY }}
          SSH_DIR: ~/.ssh
          SSH_PRIVATE_KEY_NAME: ec2_ssh_key
          SSH_CONFIG: config
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: set env variables for docker-compose
        run: |
          cd ${WORK_DIR}
          echo "LATEST_IMAGE=$LATEST_IMAGE" >> .env
          echo "PORT=$PORT" >> .env
          echo "NGINX_ENVSUBST_TEMPLATE_DIR=${ENV_REPO_CHECKOUT_PATH}/nginx-config/" >> .env
 
      - name: run commands on ec2 through ssh
        run: |
          export DOCKER_HOST="ssh://${EC2_USERNAME}@${EC2_IP}"
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker-compose down
          docker-compose up
          unset DOCKER_HOST