# This workflow notifies out env repo that a PR was merged to main, from this we trigger deployments
name: Notify PR Merged To Main

# Only trigger, when the build workflow succeeded
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  post-to-env-repo:
    runs-on: ubuntu-latest

    steps:
      - name: set post request
      - run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer <YOUR-TOKEN>" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/Kojolika/Portfolio-devops-environments/dispatches \
        -d '{"event_type":"pr-merged-to-main","client_payload":{"build":${BUILD},"version":${VERSION}}}'
      
      env:
        BUILD: ""
        VERSION: ""
        TOKEN: ${{ secrets.ENVIRONMENT_REPO_ACCESS_TOKEN }}
